import Head from "next/head";
import {
  Button,
  Card,
  CardActions,
  CardContent,
  CardMedia,
  Typography,
} from "@material-ui/core";
import { Product, products } from "@/model";

export default function ProductsListPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

          <Typography
            component="h1"
            variant="h3"
            color="textPrimary"
            gutterBottom
          >
            Produtos
          </Typography>
          {products.map((product) => (
            <Card key={product.id}>
              <CardMedia image={product.image_url} />
              <CardContent>
                <Typography component="h2" variant="h5" gutterBottom>
                  {product.name}
                </Typography>
              </CardContent>
              <CardActions>
                <Button size="small" color="primary" component="a">
                  Detalhes
                </Button>
              </CardActions>
            </Card>
          ))}
    </>
  );
}
