import Head from "next/head";
import styles from "@/styles/Home.module.css";
import {
  Button,
  Card,
  CardActions,
  CardContent,
  CardMedia,
  Typography,
} from "@material-ui/core";
import { Product } from "@/model";

const products: Product[] = [
  {
    id: "uuid",
    name: "produto",
    description: "descrição produto",
    price: 49.99,
    image_url: "https://source.unsplash.com/random?product",
    slug: "produto-teste",
    created_at: "2023-01-19T00:00:00",
  },
];

export default function ProductsListPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.container}>
          <Typography
            component="h1"
            variant="h3"
            color="textPrimary"
            gutterBottom
          >
            Produtos
          </Typography>
          {products.map((product) => (
            <Card key={product.id}>
              <CardMedia image={product.image_url} />
              <CardContent>
                <Typography component="h2" variant="h5" gutterBottom>
                  {product.name}
                </Typography>
              </CardContent>
              <CardActions>
                <Button size="small" color="primary" component="a">
                  Detalhes
                </Button>
              </CardActions>
            </Card>
          ))}
        </div>
      </main>
    </>
  );
}
