import Head from "next/head";
import {
  Button,
  Card,
  CardActions,
  CardContent,
  CardHeader,
  CardMedia,
  Typography,
} from "@material-ui/core";
import { Product, products } from "@/model";
import { NextPage } from "next";

interface ProductDetailPageProps {
  product: Product;
}

//const ProductDetailPage: NextPage<ProductDetailPageProps> = ({product,}) => {
const ProductDetailPage = () => {
  const product = products[0];

  return (
    <>
      <Head>
        <title>{product.name} - Detalhes do produto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card>
        <CardHeader
          title={product.name.toUpperCase()}
          subheader={`R$ ${product.price}`}
        />
        <CardActions>
          <Button size="small" color="primary" component="a">
            Comprar
          </Button>
        </CardActions>
        <CardMedia style={{paddingTop: '50%'}} image={product.image_url} />
        <CardContent>
          <Typography variant="body2" color="textSecondary" component="p">
            {product.description}
          </Typography>
        </CardContent>
      </Card>
    </>
  );
};

export default ProductDetailPage;
